### ISSUE TITLE
Add microcontroller power components to board inc. regulator

### ISSUE THREAD

**Issue by markrusciano** [ISU-MAVRIC/MAVRIC_Main#10]
Using the Arm Board schematic as reference, add a 3.3V regulator to the board and connect them to the microcontroller. Use the AOZ1280 regulator. The STM32F401 datasheet is in the MAVRIC_Arm repository for power reference. Page 57 has a nice overview.

**Comment by djmallek** [comment]
Layed out the STM pins, created the 3.3v regulator, hooked up 3.3v to microcontroller, and hooked up an oscillator.
