### ISSUE TITLE
Add RJ45 connectors to schematic

### ISSUE THREAD

**Issue by markrusciano** [ISU-MAVRIC/MAVRIC_Main#12]
- [x] Wheel Pods 1-6
- [x] Arm control board

**Comment by markrusciano** [comment]
Updated requirements:
- [ ] One jack for wheel pods left (we are splicing the three together) 
- [ ] One jack for wheel pods right (splicing the three wheel pods together)
- [ ] One jack for Arm Control Board
- [ ] One spare jack

**Comment by djmallek** [comment]
Changed spare RS485 to RS232
