### ISSUE TITLE
Add Vernier Sensors to Board

### ISSUE THREAD

**Issue by markrusciano** [ISU-MAVRIC/MAVRIC_Main#14]
Sparkfun Board: http://www.vernier.com/products/interfaces/bt-ard/
- [x] pH sensor
   - [x] Figure out how to scale voltage (goes through a Vernier BNC amplifier)
   - [x] Create schematic part and board footprint for the analog British telecom plug
   - [x] Add to board, assign analog port in _cube_
- [x] Soil Moisture Sensor
 - [x] Figure out how to scale voltage (goes through a Vernier BNC amplifier)
 - [x] Add to board, assign analog port in _cube_

**Comment by markrusciano** [comment]
Notes on 5V to 3.3V on Page 38 here
http://www.newark.com/pdfs/techarticles/microchip/3_3vto5vAnalogTipsnTricksBrchr.pdf

**Comment by markrusciano** [comment]
Ordered bta jacks for testing on breadboard
https://www.sparkfun.com/products/12753

**Comment by djmallek** [comment]
Hardware is done.
